# Site settings
title: Sean Johnson
description: Crafting Solutions for a Better Tomorrow
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "sjohnson1021.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sean Johnson
user_description: I'm a full stack web developer with a passion for creating user-friendly solutions to real-world problems. With a lifelong love of programming and a curiosity for emerging technologies, I'm currently exploring Python, graph databases, and natural language processing to interact with artificial intelligence and build exceptional web applications.
user_title: Software Developer
email: sjohnson1021@outlook.com
twitter_username: lorem_ipsum
github_username:  sjohnson1021
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
